import type { Curso, Usuario, Inscripcion, Notificacion } from "./types"

export const mockUser: Usuario = {
  id: "1",
  nombre: "Carlos",
  apellido: "Mendoza",
  identificacion: "1234567890",
  email: "carlos.mendoza@universidad.edu",
  rol: "ESTUDIANTE",
  programa: "Ingeniería de Sistemas",
  semestre: 5,
}

export const mockCursos: Curso[] = [
  {
    id: "1",
    codigo: "IS-501",
    nombre: "Inteligencia Artificial",
    programa: "Ingeniería de Sistemas",
    periodo: "2025-1",
    descripcion: "Fundamentos de IA, aprendizaje automático y redes neuronales.",
    creditos: 4,
    activo: true,
    esExtension: false,
    costo: 1500000,
    inscripcionInicio: "2025-01-15T00:00:00Z",
    inscripcionFin: "2025-02-15T00:00:00Z",
    grupos: [
      {
        codigoGrupo: "A",
        profesorNombre: "Dr. María García",
        cupoMaximo: 30,
        inscritosActuales: 25,
        horarios: [
          { dia: "Lunes", horaInicio: "08:00", horaFin: "10:00", salon: "Lab 301" },
          { dia: "Miércoles", horaInicio: "08:00", horaFin: "10:00", salon: "Lab 301" },
        ],
      },
      {
        codigoGrupo: "B",
        profesorNombre: "Dr. Juan Pérez",
        cupoMaximo: 30,
        inscritosActuales: 18,
        horarios: [
          { dia: "Martes", horaInicio: "14:00", horaFin: "16:00", salon: "Lab 302" },
          { dia: "Jueves", horaInicio: "14:00", horaFin: "16:00", salon: "Lab 302" },
        ],
      },
    ],
  },
  {
    id: "2",
    codigo: "IS-502",
    nombre: "Bases de Datos Avanzadas",
    programa: "Ingeniería de Sistemas",
    periodo: "2025-1",
    descripcion: "NoSQL, optimización de consultas y arquitecturas distribuidas.",
    creditos: 3,
    activo: true,
    esExtension: false,
    costo: 1200000,
    inscripcionInicio: "2025-01-15T00:00:00Z",
    inscripcionFin: "2025-02-15T00:00:00Z",
    grupos: [
      {
        codigoGrupo: "A",
        profesorNombre: "Ing. Ana Rodríguez",
        cupoMaximo: 35,
        inscritosActuales: 35,
        horarios: [
          { dia: "Lunes", horaInicio: "10:00", horaFin: "12:00", salon: "Aula 205" },
          { dia: "Viernes", horaInicio: "10:00", horaFin: "12:00", salon: "Aula 205" },
        ],
      },
    ],
  },
  {
    id: "3",
    codigo: "IS-503",
    nombre: "Desarrollo Web Full Stack",
    programa: "Ingeniería de Sistemas",
    periodo: "2025-1",
    descripcion: "React, Node.js, APIs REST y despliegue en la nube.",
    creditos: 4,
    activo: true,
    esExtension: false,
    costo: 1500000,
    inscripcionInicio: "2025-01-15T00:00:00Z",
    inscripcionFin: "2025-02-15T00:00:00Z",
    grupos: [
      {
        codigoGrupo: "A",
        profesorNombre: "Ing. Roberto Sánchez",
        cupoMaximo: 25,
        inscritosActuales: 20,
        horarios: [
          { dia: "Martes", horaInicio: "08:00", horaFin: "10:00", salon: "Lab 401" },
          { dia: "Jueves", horaInicio: "08:00", horaFin: "10:00", salon: "Lab 401" },
        ],
      },
    ],
  },
  {
    id: "4",
    codigo: "IS-504",
    nombre: "Seguridad Informática",
    programa: "Ingeniería de Sistemas",
    periodo: "2025-1",
    descripcion: "Criptografía, hacking ético y protección de sistemas.",
    creditos: 3,
    activo: true,
    esExtension: false,
    costo: 1300000,
    inscripcionInicio: "2025-01-15T00:00:00Z",
    inscripcionFin: "2025-02-15T00:00:00Z",
    grupos: [
      {
        codigoGrupo: "A",
        profesorNombre: "Dr. Luis Martínez",
        cupoMaximo: 20,
        inscritosActuales: 15,
        horarios: [{ dia: "Miércoles", horaInicio: "14:00", horaFin: "17:00", salon: "Lab 501" }],
      },
    ],
  },
  {
    id: "5",
    codigo: "EXT-001",
    nombre: "Machine Learning con Python",
    programa: "Extensión",
    periodo: "2025-1",
    descripcion: "Curso intensivo de ML con scikit-learn y TensorFlow.",
    creditos: 2,
    activo: true,
    esExtension: true,
    costo: 800000,
    inscripcionInicio: "2025-01-15T00:00:00Z",
    inscripcionFin: "2025-02-15T00:00:00Z",
    grupos: [
      {
        codigoGrupo: "A",
        profesorNombre: "Ing. Patricia López",
        cupoMaximo: 40,
        inscritosActuales: 28,
        horarios: [{ dia: "Sábado", horaInicio: "08:00", horaFin: "12:00", salon: "Auditorio B" }],
      },
    ],
  },
  {
    id: "6",
    codigo: "IS-505",
    nombre: "Cloud Computing",
    programa: "Ingeniería de Sistemas",
    periodo: "2025-1",
    descripcion: "AWS, Azure, arquitecturas serverless y contenedores.",
    creditos: 3,
    activo: true,
    esExtension: false,
    costo: 1400000,
    inscripcionInicio: "2025-01-15T00:00:00Z",
    inscripcionFin: "2025-02-15T00:00:00Z",
    grupos: [
      {
        codigoGrupo: "A",
        profesorNombre: "Dr. Fernando Ruiz",
        cupoMaximo: 30,
        inscritosActuales: 22,
        horarios: [
          { dia: "Lunes", horaInicio: "14:00", horaFin: "16:00", salon: "Lab 302" },
          { dia: "Miércoles", horaInicio: "14:00", horaFin: "16:00", salon: "Lab 302" },
        ],
      },
    ],
  },
]

export const mockInscripciones: Inscripcion[] = [
  {
    id: "1",
    estudianteId: "1",
    cursoId: "1",
    codigoGrupo: "A",
    fechaInscripcion: "2025-01-20T10:30:00Z",
    estado: "CONFIRMADA",
    curso: mockCursos[0],
  },
  {
    id: "2",
    estudianteId: "1",
    cursoId: "3",
    codigoGrupo: "A",
    fechaInscripcion: "2025-01-21T14:15:00Z",
    estado: "PENDIENTE_PAGO",
    curso: mockCursos[2],
  },
]

export const mockNotificaciones: Notificacion[] = [
  {
    id: "1",
    usuarioId: "1",
    mensaje: "Tu inscripción al curso Inteligencia Artificial ha sido confirmada.",
    tipo: "INSCRIPCION",
    leida: false,
    fechaCreacion: "2025-01-20T10:35:00Z",
  },
  {
    id: "2",
    usuarioId: "1",
    mensaje: "Recuerda que el pago del curso Desarrollo Web Full Stack vence en 3 días.",
    tipo: "PAGO",
    leida: false,
    fechaCreacion: "2025-01-22T09:00:00Z",
  },
  {
    id: "3",
    usuarioId: "1",
    mensaje: "Se ha abierto un nuevo grupo para el curso Bases de Datos Avanzadas.",
    tipo: "CURSO",
    leida: true,
    fechaCreacion: "2025-01-19T16:00:00Z",
  },
]
